---
- name: Install HTTP server
  become: yes
  hosts: g1
   
  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present
      when: amsible_distribution == "RedHat" or ansible_distribution == "Amazon"

    - name: start httpd
      service:
        name: httpd
        state: started
      when: amsible_distribution == "RedHat" or ansible_distribution == "Amazon"

    - name: enable httpd
      service:
        name: httpd
        enabled: yes
      when: amsible_distribution == "RedHat" or ansible_distribution == "Amazon"

    - name: Install Apache2
      apt:
        name: apache2
        state: present
      when: amsible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: start apache2
      service:
        name: apache2
        state: started
      when: amsible_distribution == "Ununtu" or ansible_distribution == "Debian"

    - name: enable apache2
      service:
        name: apache2
        enabled: yes
      when: amsible_distribution == "Ubuntu" or ansible_distribution == "Debian"
...
